"""agrega notas en appointments

Revision ID: bd2a0bfa1b8d
Revises: 833edbb8780a
Create Date: 2026-09-23 23:53:48.907551

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "bd2a0bfa1b8d"
down_revision: str | Sequence[str] | None = "833edbb8780a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointment",
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "notes")
    # ### end Alembic commands ###
